/**
 * Master Tenant-Management API
 * A web API to create tenants
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Order } from './order';
import { Filter } from './filter';


export interface GetTenantsQuery { 
    pageNumber?: number;
    pageSize?: number;
    orderBy?: Order;
    fields?: Array<string> | null;
    filters?: Array<Filter> | null;
}

