/**
 * Master Tenant-Management API
 * A web API to create tenants
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TenantDTO } from './tenantDTO';


export interface TenantDTOIEnumerablePagedResponse { 
    succeeded?: boolean;
    message?: string;
    errors?: Array<string>;
    data?: Array<TenantDTO>;
    pageNumber?: number;
    pageSize?: number;
    recordsFiltered?: number;
    recordsTotal?: number;
}

